export const courses = [
  {
    id: 1,
    slug: "react-js",
    title: "آموزش جامع React.js از مقدماتی تا پیشرفته",
    teacher: "سبحان سوقندی",
    banner: "/images/course.jpg",
    course_level: "مقدماتی تا پیشرفته",
    course_hour: "۲۸ ساعت",
    price: 2450000,
    is_free: false,
    status: "پرفروش",
  },
  {
    id: 2,
    slug: "laravel",
    title: "آموزش Laravel پروژه محور",
    teacher: "محمد احمدی",
    banner: "/images/course.jpg",
    course_level: "متوسط",
    course_hour: "۱۸ ساعت",
    price: 0,
    is_free: true,
    status: "رایگان",
  },
  {
    id: 3,
    slug: "python",
    title: "آموزش جامع Python",
    teacher: "علی رضایی",
    banner: "/images/course.jpg",
    course_level: "مقدماتی",
    course_hour: "۳۵ ساعت",
    price: 1890000,
    is_free: false,
    status: "جدید",
  },
];